tasks:
  - before: wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - init: sudo dpkg -i packages-microsoft-prod.deb && rm packages-microsoft-prod.deb
  - command: sudo apt-get update
  - command: sudo apt-get install -y dotnet-sdk-6.0